/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import static vistas.InicioVista.mainPanel;
import simulacion.Simulacion;
import vistas.FormularioVista;
/**
 *
 * @author Jose Andres
 */
public class EstadisticasVista extends javax.swing.JPanel {

    /**
     * Creates new form EstadisticasVista
     */
    public EstadisticasVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        costoServidorTabla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        porcentajeUtilizacionTabla = new javax.swing.JTable();
        tiempoPromClienteSistema = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cantClientesNoEsperaLabel = new javax.swing.JLabel();
        cantPromedioClientesColaLabel = new javax.swing.JLabel();
        cantPromedioClientesSistemaLabel = new javax.swing.JLabel();
        tiempoPromClienteColaLabel = new javax.swing.JLabel();
        clienteHaceColaLabel = new javax.swing.JLabel();
        probEsperaLabel = new javax.swing.JLabel();
        utilizacionGeneralLabel = new javax.swing.JLabel();
        cantClientesNoAtendidosLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        costoPromEsperaLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Resultados de la simulación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Tiempo promedio de un cliente en el sistema: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 330, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Cantidad Cientes que no esperan:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 250, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Costo de cada servidor");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 170, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Probabilidad de esperar: ");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 180, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Cantidad Promedio de clientes en cola: ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 290, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Cantidad Promedio de clientes en sistema: ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 320, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Utilizacion general: ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 160, -1));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Tiempo promedio de un cliente en cola:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 290, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Tiempo promedio de un cliente que hace cola:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 20, 370));

        costoServidorTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Servidor", "Costo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(costoServidorTabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 270, 100));

        porcentajeUtilizacionTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Servidor", "Porcentaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(porcentajeUtilizacionTabla);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 270, 90));

        tiempoPromClienteSistema.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tiempoPromClienteSistema.setForeground(new java.awt.Color(102, 102, 102));
        tiempoPromClienteSistema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tiempoPromClienteSistema.setText("00");
        add(tiempoPromClienteSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 70, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Porcentaje de utilizacion de cada servidor");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 300, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Cantidad Clientes que se van sin ser atendidos: ");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 340, -1));

        cantClientesNoEsperaLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cantClientesNoEsperaLabel.setForeground(new java.awt.Color(102, 102, 102));
        cantClientesNoEsperaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cantClientesNoEsperaLabel.setText("00");
        add(cantClientesNoEsperaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 70, -1));

        cantPromedioClientesColaLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cantPromedioClientesColaLabel.setForeground(new java.awt.Color(102, 102, 102));
        cantPromedioClientesColaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cantPromedioClientesColaLabel.setText("00");
        add(cantPromedioClientesColaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 80, -1));

        cantPromedioClientesSistemaLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cantPromedioClientesSistemaLabel.setForeground(new java.awt.Color(102, 102, 102));
        cantPromedioClientesSistemaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cantPromedioClientesSistemaLabel.setText("00");
        add(cantPromedioClientesSistemaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 70, -1));

        tiempoPromClienteColaLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tiempoPromClienteColaLabel.setForeground(new java.awt.Color(102, 102, 102));
        tiempoPromClienteColaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tiempoPromClienteColaLabel.setText("00");
        add(tiempoPromClienteColaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 70, -1));

        clienteHaceColaLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        clienteHaceColaLabel.setForeground(new java.awt.Color(102, 102, 102));
        clienteHaceColaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        clienteHaceColaLabel.setText("00");
        add(clienteHaceColaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 60, -1));

        probEsperaLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        probEsperaLabel.setForeground(new java.awt.Color(102, 102, 102));
        probEsperaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        probEsperaLabel.setText("00");
        add(probEsperaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 70, -1));

        utilizacionGeneralLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        utilizacionGeneralLabel.setForeground(new java.awt.Color(102, 102, 102));
        utilizacionGeneralLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        utilizacionGeneralLabel.setText("00");
        add(utilizacionGeneralLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 90, -1));

        cantClientesNoAtendidosLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cantClientesNoAtendidosLabel.setForeground(new java.awt.Color(102, 102, 102));
        cantClientesNoAtendidosLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cantClientesNoAtendidosLabel.setText("00");
        add(cantClientesNoAtendidosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Costo promedio de espera: ");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 210, -1));

        costoPromEsperaLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        costoPromEsperaLabel.setForeground(new java.awt.Color(102, 102, 102));
        costoPromEsperaLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        costoPromEsperaLabel.setText("00");
        add(costoPromEsperaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 70, -1));

        jPanel2.setBackground(new java.awt.Color(125, 202, 131));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Volver al formulario");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarFormulario(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 140, 40));

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ver tabla de eventos");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarTablaEventos(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarTablaEventos(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarTablaEventos
    
        //TablaEventosVista tablaVista = new TablaEventosVista();
        
        simulacion.Simulacion.tablaEventosVista.setSize(800,500);
        mainPanel.removeAll();
        mainPanel.add(simulacion.Simulacion.tablaEventosVista);
        mainPanel.revalidate();
        mainPanel.repaint();
    }//GEN-LAST:event_mostrarTablaEventos

    private void mostrarFormulario(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarFormulario
        FormularioVista formulario = new FormularioVista();
        formulario.setSize(800,500);
        mainPanel.removeAll();
        mainPanel.add(formulario);
        mainPanel.revalidate();
        mainPanel.repaint();
        
    }//GEN-LAST:event_mostrarFormulario


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel cantClientesNoAtendidosLabel;
    public static javax.swing.JLabel cantClientesNoEsperaLabel;
    public static javax.swing.JLabel cantPromedioClientesColaLabel;
    public static javax.swing.JLabel cantPromedioClientesSistemaLabel;
    public static javax.swing.JLabel clienteHaceColaLabel;
    public static javax.swing.JLabel costoPromEsperaLabel;
    public static javax.swing.JTable costoServidorTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTable porcentajeUtilizacionTabla;
    public static javax.swing.JLabel probEsperaLabel;
    public static javax.swing.JLabel tiempoPromClienteColaLabel;
    public static javax.swing.JLabel tiempoPromClienteSistema;
    public static javax.swing.JLabel utilizacionGeneralLabel;
    // End of variables declaration//GEN-END:variables
}
