/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import static javax.swing.GroupLayout.Alignment.CENTER;

/**
 *
 * @author Jose Andres
 */
public class InicioVista extends javax.swing.JFrame {

    /**
     * Creates new form TimeForm
     */
    
    public FormularioVista tiempoPanel;
    
    
    public InicioVista() {
        initComponents();
        /*this.tiempoPanel = new TiempoPanel();
        tiempoPanel.setSize(520,430);
        this.principalPanel.removeAll();
        this.principalPanel.add(tiempoPanel, BorderLayout.CENTER);
        this.principalPanel.repaint();*/
        this.panelParte1.addMouseListener(new MouseListener() {
            public void mousePressed(MouseEvent me) { }
            public void mouseReleased(MouseEvent me) { }
            public void mouseEntered(MouseEvent me) { 
                me.getComponent().setBackground(new Color(102,153,255));
                topPart1.setForeground(Color.white);
                numeroPart1.setForeground(Color.white);
            }
            public void mouseExited(MouseEvent me) { 
                me.getComponent().setBackground(Color.white);
                topPart1.setForeground(Color.black);
                numeroPart1.setForeground(Color.black);
            }
            public void mouseClicked(MouseEvent me) { }
        });
        this.panelParte2.addMouseListener(new MouseListener() {
            public void mousePressed(MouseEvent me) { }
            public void mouseReleased(MouseEvent me) { }
            public void mouseEntered(MouseEvent me) { 
                me.getComponent().setBackground(new Color(102,153,255));
                topPart2.setForeground(Color.white);
                numeroPart2.setForeground(Color.white);
            }
            public void mouseExited(MouseEvent me) { 
                me.getComponent().setBackground(Color.white);
                topPart2.setForeground(Color.black);
                numeroPart2.setForeground(Color.black);
            }
            public void mouseClicked(MouseEvent me) { }
        });
        this.salirBoton.addMouseListener(new MouseListener() {
            public void mousePressed(MouseEvent me) { }
            public void mouseReleased(MouseEvent me) { }
            public void mouseEntered(MouseEvent me) { 
                me.getComponent().setBackground(new Color(255,51,51));
            }
            public void mouseExited(MouseEvent me) { 
                me.getComponent().setBackground(new Color(255,102,102));
            }
            public void mouseClicked(MouseEvent me) { }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        panelParte2 = new javax.swing.JPanel();
        numeroPart2 = new javax.swing.JLabel();
        topPart2 = new javax.swing.JLabel();
        panelParte1 = new javax.swing.JPanel();
        topPart1 = new javax.swing.JLabel();
        numeroPart1 = new javax.swing.JLabel();
        salirBoton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        principalPanel.setBackground(new java.awt.Color(255, 255, 255));
        principalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelParte2.setBackground(new java.awt.Color(255, 255, 255));

        numeroPart2.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        numeroPart2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroPart2.setText("II");

        topPart2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        topPart2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topPart2.setText("PARTE");

        javax.swing.GroupLayout panelParte2Layout = new javax.swing.GroupLayout(panelParte2);
        panelParte2.setLayout(panelParte2Layout);
        panelParte2Layout.setHorizontalGroup(
            panelParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParte2Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(panelParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroPart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topPart2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        panelParte2Layout.setVerticalGroup(
            panelParte2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParte2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(topPart2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numeroPart2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        principalPanel.add(panelParte2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, 228));

        panelParte1.setBackground(new java.awt.Color(255, 255, 255));

        topPart1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        topPart1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        topPart1.setText("PARTE");

        numeroPart1.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        numeroPart1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numeroPart1.setText("I");

        javax.swing.GroupLayout panelParte1Layout = new javax.swing.GroupLayout(panelParte1);
        panelParte1.setLayout(panelParte1Layout);
        panelParte1Layout.setHorizontalGroup(
            panelParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParte1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numeroPart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topPart1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelParte1Layout.setVerticalGroup(
            panelParte1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParte1Layout.createSequentialGroup()
                .addComponent(topPart1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(numeroPart1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        principalPanel.add(panelParte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 230));

        salirBoton.setBackground(new java.awt.Color(255, 102, 102));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Salir");

        javax.swing.GroupLayout salirBotonLayout = new javax.swing.GroupLayout(salirBoton);
        salirBoton.setLayout(salirBotonLayout);
        salirBotonLayout.setHorizontalGroup(
            salirBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salirBotonLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        salirBotonLayout.setVerticalGroup(
            salirBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salirBotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        principalPanel.add(salirBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 470, 60));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Proyecto de Simulación ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        principalPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        principalPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 10, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioVista().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel numeroPart1;
    public javax.swing.JLabel numeroPart2;
    public javax.swing.JPanel panelParte1;
    public javax.swing.JPanel panelParte2;
    public javax.swing.JPanel principalPanel;
    public javax.swing.JPanel salirBoton;
    public javax.swing.JLabel topPart1;
    public javax.swing.JLabel topPart2;
    // End of variables declaration//GEN-END:variables
}
